### ISSUE TITLE
Causing Boot freeze on Pixel 4a 5G

### ISSUE THREAD

**Issue by BilliTheKid** [kdrag0n/proton_kernel_redbull#1]
Flashed this today. Cause a boot freeze on the Google logo on Google 4a 5G.

**Comment by kdrag0n** [comment]
How exactly did you flash it?

**Comment by BilliTheKid** [comment]
It's ok, i sorted it with fastboot. I tried flashing it with EX Manager and that caused the issue. Hopefully with the next version you could make it easier to flash it with the manager.

**Comment by kdrag0n** [comment]
There are no plans to do so, my bootable flasher is much faster and easy to use than flashable ZIPs in my opinion. Additionally, flashable ZIPs are currently only possible to flash using proprietary paid apps from the Play Store. Not everyone is willing to (or even able to) buy and use such apps just to flash a kernel.
