### ISSUE TITLE
Kernal issue

### ISSUE THREAD

**Issue by Pixel5user** [kdrag0n/proton_kernel_redbull#2]
Hi, ive flased your ROM and kernal onto my P5. Everything is great apart from this annoying pop up that I can not stop. 

"SIM Manager keeps stopping"

When I click app info. I see under details Sim Manager and Z-Ram

I noticed another user has been having the same issue but I cant see that anyone has offered a solution as yet. Is there anything I can do?

**Comment by kdrag0n** [comment]
Your issue is not related to this kernel.

**Comment by Pixel5user** [comment]
Oh, if you could tell me what it is or how to solve the issue it would be greatly appreciated. Have you come across this before with another user of yur fine work?

**Comment by Pixel5user** [comment]
Danny, if its not the Kernel do you know what it is? Your work is really good the battery is lasting over a week on this phone now. If the kernal is not causing this issue what is? Im not the only one having this problem? Do you knot know how to solve it yet?

**Comment by kdrag0n** [comment]
Sorry for not giving you the solution, someone else opened the exact same issue on one of my ROM repositories today and I answered there with the assumption that it was from the same person.

You can find the solution here: https://github.com/ProtonAOSP/android_device_google_redbull/issues/3
