### ISSUE TITLE
Rom issue

### ISSUE THREAD

**Issue by Pixel5user** [kdrag0n/proton_kernel_redbull#3]
Upon instalation I repeatedly receved a pop up error on the P5 "SIM MANAGER ERROR" do you know what it is, I was told that it is not the kernal flashed so it can only be an issue this. Your work is excellent if you could solve this issue Iwe would all be greatful or rather tell us were we are going wrong?

**Comment by kdrag0n** [comment]
Sorry, I didn't notice this issue until now. That issue has been documented at https://protonaosp.kdrag0n.dev/faq#sim-manager-crashing, but in the future, please don't open issues for ProtonAOSP on the Proton Kernel repo.
