### ISSUE TITLE
Any plans to merge Barbet in to this tree? 

### ISSUE THREAD

**Issue by ohmybahgosh** [kdrag0n/proton_kernel_redbull#4]
I noticed GrapheneOS has recently updated their redbull device tree to include the pixel 5a (barbet) and I was wondering if you have any plans on doing the same?  Would love to use this kernel on my 5a!

https://github.com/GrapheneOS/device_google_redbull

**Comment by kdrag0n** [comment]
It's possible, but I'm going to close this issue for now because it's a feature request with no definite plans.
